[package]
name = "day08"
version = "0.1.0"
edition = "2021"

[dependencies]
aocutils = { version = "0.1.0", path = "../aocutils" }
colored = "2.1.0"
itertools = "0.13.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
